version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  web:
    build: .
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://root:mypassword@db:3306/mydb
    ports:
      - "5000:5000"
    depends_on:
      - db